#' @title Fetch PayPal Transactions with Adaptive Chunking
#'
#' @description Extracts transaction details from the PayPal Reporting API.
#' Uses an adaptive approach: attempts to fetch a full day first. Only if the
#' daily limit (10,000 items) is breached, it dynamically splits that specific
#' day into 4-hour chunks. Drastically reduces API calls and prevents 429 errors.
#'
#' @param token Character. The OAuth 2.0 Access Token generated by `get_paypal_token()`.
#' @param start_date Date or Character (YYYY-MM-DD). The start of the reporting window.
#' @param end_date Date or Character (YYYY-MM-DD). The end of the reporting window.
#' @param base_url Character. The PayPal API base URL. Defaults to the environment variable.
#'
#' @return A flattened `data.frame` containing all transaction details.
#' @export
#'
#' @importFrom httr RETRY add_headers status_code content
#' @importFrom jsonlite fromJSON
#' @importFrom dplyr bind_rows
#'
#' @examples \dontrun{
#' token <- get_paypal_token()
#' df_paypal <- get_paypal_transactions(token, Sys.Date() - 30, Sys.Date())
#' }
get_paypal_transactions <- function(token,
                                    start_date,
                                    end_date,
                                    base_url = Sys.getenv("PAYPAL_BASE_URL")) {
  if (missing(token)) {
    stop("PayPal access token is missing. Please provide a valid token.")
  }

  start_date <- as.Date(start_date)
  end_date <- as.Date(end_date)

  if (start_date > end_date) stop("Das Startdatum darf nicht nach dem Enddatum liegen.")

  date_seq <- seq(start_date, end_date, by = "day")
  all_transactions <- list()

  # --- INTERNE HILFSFUNKTION FÜR DEN API-CALL ---
  fetch_window <- function(t_start, t_end) {
    current_page <- 1
    total_pages <- 1
    window_data <- list()

    while (current_page <= total_pages) {
      response <- httr::RETRY(
        verb = "GET",
        url = paste0(base_url, "/v1/reporting/transactions"),
        query = list(start_date = t_start, end_date = t_end, fields = "all", page_size = 100, page = current_page),
        httr::add_headers(Authorization = paste("Bearer", token)),
        times = 5, pause_base = 3, pause_cap = 60,
        terminate_on = c(400, 401, 403, 404) # Bei 400 direkt abbrechen, nicht retrien!
      )

      status <- httr::status_code(response)
      res_text <- httr::content(response, as = "text", encoding = "UTF-8")

      # Wenn zu groß: Abbruch und Signal an Hauptschleife
      if (status == 400 && grepl("RESULTSET_TOO_LARGE", res_text)) {
        return(list(status = "TOO_LARGE", data = NULL))
      } else if (status != 200) {
        stop(sprintf("API Error %s im Fenster %s: %s", status, t_start, res_text))
      }

      parsed <- jsonlite::fromJSON(res_text, flatten = TRUE)

      if (!is.null(parsed$transaction_details) && nrow(parsed$transaction_details) > 0) {
        window_data[[current_page]] <- parsed$transaction_details
      }
      total_pages <- ifelse(is.null(parsed$total_pages), 0, parsed$total_pages)
      current_page <- current_page + 1
    }

    if (length(window_data) > 0) {
      return(list(status = "SUCCESS", data = dplyr::bind_rows(window_data)))
    } else {
      return(list(status = "SUCCESS", data = data.frame()))
    }
  }
  # --- ENDE HILFSFUNKTION ---

  message(sprintf("Starte Adaptive Chunking Extraktion fuer %s Tage...", length(date_seq)))

  # HAUPTSCHLEIFE ÜBER JEDEN TAG
  for (i in seq_along(date_seq)) {
    current_date <- date_seq[i]
    start_str <- format(as.POSIXct(paste0(current_date, " 00:00:00"), tz = "UTC"), "%Y-%m-%dT%H:%M:%SZ")
    end_str <- format(as.POSIXct(paste0(current_date, " 23:59:59"), tz = "UTC"), "%Y-%m-%dT%H:%M:%SZ")

    message(sprintf("[%s/%s] Pruefe %s (Ganzer Tag)...", i, length(date_seq), current_date))
    res <- fetch_window(start_str, end_str)

    # WENN DER TAG ZU GROSS IST -> SUB-DAILY CHUNKING FÜR DIESEN TAG
    if (res$status == "TOO_LARGE") {
      message(sprintf(" -> %s ueberschreitet Limit! Splitte Tag in 4-Stunden-Bloecke...", current_date))

      time_seq <- seq(as.POSIXct(paste0(current_date, " 00:00:00"), tz = "UTC"),
        as.POSIXct(paste0(current_date, " 23:59:59"), tz = "UTC"),
        by = "4 hours"
      )

      for (j in seq_along(time_seq)) {
        sub_start <- time_seq[j]
        sub_end <- min(sub_start + (4 * 3600) - 1, as.POSIXct(paste0(current_date, " 23:59:59"), tz = "UTC"))

        sub_start_str <- format(sub_start, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
        sub_end_str <- format(sub_end, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")

        message(sprintf("    -> Lade Block %s bis %s...", format(sub_start, "%H:%M"), format(sub_end, "%H:%M")))

        sub_res <- fetch_window(sub_start_str, sub_end_str)
        if (nrow(sub_res$data) > 0) {
          all_transactions[[sub_start_str]] <- sub_res$data
        }
        Sys.sleep(1) # Kurze Pause zwischen den Blöcken
      }
    } else {
      # TAG WAR NORMAL -> EINFACH SPEICHERN
      if (nrow(res$data) > 0) {
        all_transactions[[start_str]] <- res$data
      }
    }

    # Standard-Pacing zwischen den Tagen
    Sys.sleep(1.5)
  }

  if (length(all_transactions) == 0) {
    message("Keine Transaktionen gefunden.")
    return(data.frame())
  }

  final_df <- dplyr::bind_rows(all_transactions)
  message(sprintf("Extraktion komplett! %s Transaktionen erfolgreich geladen.", nrow(final_df)))

  return(final_df)
}
